<a href="https://colab.research.google.com/github/maxmatical/fast.ai/blob/master/fastai_%2B_blurr_%2B_deberta_classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
%%capture
!pip install --upgrade fastai
!pip install transformers
!pip install ohmeow-blurr
!pip install bentoml

In [2]:
from fastai.test_utils import show_install
show_install()



```text
=== Software === 
python        : 3.7.10
fastai        : 2.2.7
fastcore      : 1.3.19
fastprogress  : 0.2.7
torch         : 1.7.1
nvidia driver : 460.32
torch cuda    : 10.2 / is available
torch cudnn   : 7605 / is enabled

=== Hardware === 
nvidia gpus   : 1
torch devices : 1
  - gpu0      : Tesla K80

=== Environment === 
platform      : Linux-4.19.112+-x86_64-with-Ubuntu-18.04-bionic
distro        : #1 SMP Thu Jul 23 08:00:38 PDT 2020
conda env     : Unknown
python        : /usr/bin/python3
sys.path      : 
/content
/env/python
/usr/lib/python37.zip
/usr/lib/python3.7
/usr/lib/python3.7/lib-dynload
/usr/local/lib/python3.7/dist-packages
/usr/lib/python3/dist-packages
/usr/local/lib/python3.7/dist-packages/IPython/extensions
/root/.ipython
```

Please make sure to include opening/closing ``` when you paste into forums/github to make the reports appear formatted as code sections.

Optional package(s) to enhance the diagnostics can be installed with:
pip install distro
Once i

In [3]:
from transformers import *
from fastai.text.all import *

from blurr.data.all import *
from blurr.modeling.all import *

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Unzipping corpora/wordnet.zip.


In [4]:
path = untar_data(URLs.IMDB_SAMPLE)

model_path = Path('models')
imdb_df = pd.read_csv(path/'texts.csv')

In [5]:
task = HF_TASKS_AUTO.SequenceClassification

pretrained_model_name = 'microsoft/deberta-base'
hf_arch, hf_config, hf_tokenizer, hf_model = BLURR_MODEL_HELPER.get_hf_objects(pretrained_model_name,  task=task)

In [6]:
# single input
blocks = (HF_TextBlock(hf_arch, hf_config, hf_tokenizer, hf_model), CategoryBlock)
dblock = DataBlock(blocks=blocks,  get_x=ColReader('text'), get_y=ColReader('label'), splitter=ColSplitter())

dls = dblock.dataloaders(imdb_df, bs=4)

In [7]:
dls.show_batch(dataloaders=dls, max_n=2)

In [8]:
model = HF_BaseModelWrapper(hf_model)

learn = Learner(dls, 
                model,
                loss_func=LabelSmoothingCrossEntropyFlat(),
                metrics=[accuracy],
                cbs=[HF_BaseModelCallback],
                splitter=hf_splitter).to_fp16()

learn.unfreeze()

cbs = [
    GradientAccumulation(n_acc=32),
    ReduceLROnPlateau(monitor='accuracy', factor=5, patience=5),
    EarlyStoppingCallback(monitor='accuracy', min_delta=0.01, patience=7),
    SaveModelCallback(monitor="accuracy", fname="model_1")
]



In [ ]:
learn.fit_one_cycle(
    3,
    lr_max=3e-5,
    cbs = cbs
)

# Inference and deployment with BentoML

Notess:
- can just treat as a fastai model and use `test_dl` and `get_preds` to make inference
- Can also quantize the underpying pytorch model with `learn.model.hf_model`

In [10]:
learn.validate()

(#2) [0.6920732259750366,0.5350000262260437]

In [14]:
test_dl = learn.dls.test_dl(["this movie sucks", "i really like this movie"])
learn.get_preds(dl=test_dl, with_decoded=True)

(tensor([[0.5109, 0.4891],
         [0.5114, 0.4886]]), None, tensor([0, 0]))

In [27]:
preds = learn.get_preds(dl=test_dl, with_decoded=True)[-1].cpu().numpy()
preds

array([0, 0])

### Using only the underlying pytorch model

allows for `torchscript` with jit 

In [ ]:
torch.save(learn.model.hf_model, "deberta.pt")
inf_model = torch.load("deberta.pt", map_location=torch.device("cpu"))
inf_model.eval()

In [37]:
text = "This movie sucks"
text_ids = hf_tokenizer.encode(text)
inp = tensor(text_ids)[None]

inf_model(inp)

SequenceClassifierOutput([('logits',
                           tensor([[0.0442, 0.0002]], grad_fn=<AddmmBackward>))])

In [47]:
texts = ["This movie sucks", "i really like this movie"]
text_ids = hf_tokenizer.batch_encode_plus(texts, 
                                          padding='longest',
                                          truncation=True,
                                          max_length=256,
                                          return_tensors="pt")

text_ids

{'input_ids': tensor([[    1,   713,  1569, 29384,     2,     0,     0],
        [    1,   118,   269,   101,    42,  1569,     2]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 0, 0],
        [1, 1, 1, 1, 1, 1, 1]])}

In [48]:
# creating pytorch dataloader
from torch.utils.data import TensorDataset, BatchSampler
input_ids_inf = text_ids['input_ids']
attention_masks_inf = text_ids['attention_mask']

dataset_inf = TensorDataset(input_ids_inf, attention_masks_inf)
dataloader_inf = DataLoader(dataset_inf, sampler=SequentialSampler(dataset_inf), batch_size=32)

In [61]:
device = "cpu"
all_logits = np.empty([0,2])

for batch in dataloader_inf:

    batch = tuple(b.to(device) for b in batch)
    inputs = {'input_ids': batch[0],
              'attention_mask': batch[1],
              }
    with torch.no_grad():        
        outputs = inf_model(**inputs)

    logits = outputs[0]

    all_logits = np.vstack([all_logits, torch.softmax(logits, dim=1).detach().cpu().numpy()])

In [53]:
all_logits

array([[0.51101547, 0.48898458],
       [0.51140863, 0.48859134]])

Now we can deploy with BentoML using either fastai or pytorch frameworks